// flow-typed signature: b91f8336b8456b7966233a948ad1c9bc
// flow-typed version: <<STUB>>/next-auth_v^1.8.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-auth/client' {
  declare module.exports: any;
}

declare module 'next-auth/example/config/next-auth.functions-mongoose' {
  declare module.exports: any;
}

declare module 'next-auth/example/index' {
  declare module.exports: any;
}

declare module 'next-auth/example/next-auth.config' {
  declare module.exports: any;
}

declare module 'next-auth/example/next-auth.functions' {
  declare module.exports: any;
}

declare module 'next-auth/example/next-auth.providers' {
  declare module.exports: any;
}

declare module 'next-auth/example/pages/auth/callback' {
  declare module.exports: any;
}

declare module 'next-auth/example/pages/auth/check-email' {
  declare module.exports: any;
}

declare module 'next-auth/example/pages/auth/credentials' {
  declare module.exports: any;
}

declare module 'next-auth/example/pages/auth/error' {
  declare module.exports: any;
}

declare module 'next-auth/example/pages/auth/index' {
  declare module.exports: any;
}

declare module 'next-auth/example/pages/index' {
  declare module.exports: any;
}

declare module 'next-auth/src/client/index' {
  declare module.exports: any;
}

declare module 'next-auth/src/client/next-auth-client' {
  declare module.exports: any;
}

declare module 'next-auth/src/passport-strategies' {
  declare module.exports: any;
}

declare module 'next-auth/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-auth/client.js' {
  declare module.exports: $Exports<'next-auth/client'>;
}
declare module 'next-auth/example/config/next-auth.functions-mongoose.js' {
  declare module.exports: $Exports<'next-auth/example/config/next-auth.functions-mongoose'>;
}
declare module 'next-auth/example/index.js' {
  declare module.exports: $Exports<'next-auth/example/index'>;
}
declare module 'next-auth/example/next-auth.config.js' {
  declare module.exports: $Exports<'next-auth/example/next-auth.config'>;
}
declare module 'next-auth/example/next-auth.functions.js' {
  declare module.exports: $Exports<'next-auth/example/next-auth.functions'>;
}
declare module 'next-auth/example/next-auth.providers.js' {
  declare module.exports: $Exports<'next-auth/example/next-auth.providers'>;
}
declare module 'next-auth/example/pages/auth/callback.js' {
  declare module.exports: $Exports<'next-auth/example/pages/auth/callback'>;
}
declare module 'next-auth/example/pages/auth/check-email.js' {
  declare module.exports: $Exports<'next-auth/example/pages/auth/check-email'>;
}
declare module 'next-auth/example/pages/auth/credentials.js' {
  declare module.exports: $Exports<'next-auth/example/pages/auth/credentials'>;
}
declare module 'next-auth/example/pages/auth/error.js' {
  declare module.exports: $Exports<'next-auth/example/pages/auth/error'>;
}
declare module 'next-auth/example/pages/auth/index.js' {
  declare module.exports: $Exports<'next-auth/example/pages/auth/index'>;
}
declare module 'next-auth/example/pages/index.js' {
  declare module.exports: $Exports<'next-auth/example/pages/index'>;
}
declare module 'next-auth/index' {
  declare module.exports: $Exports<'next-auth'>;
}
declare module 'next-auth/index.js' {
  declare module.exports: $Exports<'next-auth'>;
}
declare module 'next-auth/src/client/index.js' {
  declare module.exports: $Exports<'next-auth/src/client/index'>;
}
declare module 'next-auth/src/client/next-auth-client.js' {
  declare module.exports: $Exports<'next-auth/src/client/next-auth-client'>;
}
declare module 'next-auth/src/passport-strategies.js' {
  declare module.exports: $Exports<'next-auth/src/passport-strategies'>;
}
declare module 'next-auth/webpack.config.js' {
  declare module.exports: $Exports<'next-auth/webpack.config'>;
}
